export const lagosLocalGovernments = [
  'AGEGE',
  'AJEROMI-IFELODUN',
  'ALIMOSHO',
  'AMUWO-ODOFIN',
  'APAPA',
  'BADAGRY',
  'EPE',
  'ETI OSA',
  'IBEJU-LEKKI',
  'IFAKO-IJAIYE',
  'IKEJA',
  'IKORODU',
  'KOSOFE',
  'LAGOS ISLAND',
  'LAGOS MAINLAND',
  'MUSHIN',
  'OJO',
  'OSHODI-ISOLO',
  'SOMOLU',
  'SURULERE',
] as const;
