export enum NotePriority {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  CRITICAL = 'CRITICAL',
}

export enum NoteCategory {
  GENERAL = 'GENERAL',
  VERIFICATION = 'VERIFICATION',
  RISK_ASSESSMENT = 'RISK_ASSESSMENT',
  COMPLIANCE = 'COMPLIANCE',
  COMMUNICATION = 'COMMUNICATION',
  DECISION = 'DECISION',
  FOLLOW_UP = 'FOLLOW_UP',
  DOCUMENTATION = 'DOCUMENTATION',
}

export enum InternalNoteType {
  APPLICATION = 'APPLICATION',
  REQUEST = 'REQUEST',
}
