export enum CATEGORY_DELETE_CHOICES {
  DELETE_CATEGORY_WITH_PRODUCTS = 'DELETE_CATEGORY_WITH_PRODUCTS',
  DELETE_CATEGORY_AND_ADD_TO_ANOTHER = 'DELETE_CATEGORY_AND_ADD_TO_ANOTHER',
  // DELETE_CATEGORY_ONLY = 'DELETE_CATEGORY_ONLY',
}
